### ISSUE TITLE
Loading images and labels issue

### ISSUE THREAD

**Issue by AdivarekarBhumit** [vitords/EMNIST-sandbox#1]
No such directory found for emnist by class files even though I have given correct file path.
And there is a mismatch error while loading the files
all the library requirements are also satisfied
Please help me with these errors
![err1](https://user-images.githubusercontent.com/26761067/31833583-9cd299ba-b5e8-11e7-8fd9-4738b7129a5f.JPG)
![err2](https://user-images.githubusercontent.com/26761067/31833591-a0a69334-b5e8-11e7-8b2f-e2145ed67369.JPG)

**Comment by vitords** [comment]
It looks like you have not extracted the `.gz` files. When you download the binary EMNIST dataset from the official website, it's in a file named `gzip.zip`. Inside it you will find the mapping files with the `.txt` format, and the data files with the `.gz` format. 

Don't forget to also extract the `.gz` files as they contain the needed data files, named exactly `emnist-byclass-test-images-idx3-ubyte`, `emnist-byclass-test-labels-idx1-ubyte`, `emnist-byclass-train-images-idx3-ubyte` and `emnist-byclass-train-labels-idx1-ubyte`.
